import { Inter} from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";

const inter = Inter({subsets: ["latin"]});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={` ${inter.className}`}
      >
        <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          > 
          
          <main className="min-h-screen">{children}</main>

          <footer className="bg-outline/50 py-12 ">
          <div className="container mx-auto text-center text-gray-200 px-4">
            <p>Made with ❤️ by Piyush Gupta</p>
          </div>
        </footer>
          
          </ThemeProvider>
       
        
      </body>
    </html>
  );
}
